### ISSUE TITLE
[Suggestion] Only resort to mojang api to retrieve uuid as last resort

### ISSUE THREAD

**Issue by Favorlock** [gpotter2/ExtraStorage#1]
As the title suggests I would recommend retrieving the player's uuid from mojang's api as a last resort. The way you currently do things is not performant, prone to errors, and frankly ignores the purpose of the player api.

Only reasoning I'm bringing this up for is because of the fact that I was experiencing server crashes due to your plugin as a result of your plugin hogging up resources on the main thread.

**Comment by gpotter2** [comment]
Hey!
I know getting players uuid from mojang api is not the best... but it is the only way to make a player keeping his bagpack even if he change his name... As the bukkit API is putting a new UUID to every player...

**Comment by gpotter2** [comment]
added here:

**Comment by Favorlock** [comment]
Sorry for the late response, didn't receive a notification. Bukkit does not change a player's UUID when they change names because Bukkit relies on Mojang assigned UUID when in online mode. There is no good reason why you shouldn't rely on bukkit api, especially since people shouldn't be using offline mode. Bukkit team even frowned upon people using offline mode because it causes more problems for plugins.

**Comment by gpotter2** [comment]
Hey

currently, if you print your bukkit UUID and your Minecraft UUID, you will
be able to see that they are differents...

It's why I though I was forced to use Minecraft UUID... Cause changing
your username changes your bukkit uuid...

I recently made an update to prevent from getting too much data in
Internet...

I added an option to select which mode you want to use, so I think every
one is happy with it...

I don't really understand what you are expecting now...

Anyway, thanks a lot for your suggestion ;)
